name: Testing gh
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version:
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get -y install yasm
      - run: sudo apt-get -y purge cmake
      - run: which cmake
      - run: cmake --version
      - run: echo $PATH
      - run: sudo apt remove cmake
      - run: sudo apt -y purge --auto-remove cmake
      - run: sudo rm -rf /usr/local/cmake-*
      - run: sudo apt remove cmake
      - run: sudo apt -y purge --auto-remove cmake
      - run: 'wget https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.sh;'
      - run: >-
          sudo sh cmake-3.20.0-linux-x86_64.sh --prefix=/usr/local
          --exclude-subdir;
      - run: 'export PATH=${PATH/''3.12.4''/''3.20.0''}'
      - run: cmake --version
      - run: sudo apt install -y build-essential
      - run: echo $PATH
      - run: python --version
      - run: python setup.py install
      - run: pip install pytest cryptg
      - run: pytest
